### ISSUE TITLE
Change error warning for missing trait name

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/traits.build#5] opened 2023-06-28 08:02 UTC
Referencing [this issue from austraits.build](https://github.com/traitecoevo/austraits.build/issues/728):

In `traits$excluded_data`, if a `trait_name` isn't found, the error is `Missing unit conversion`. It should be changed to be `Trait name incorrect` (or similar).

There are also correct instances of the error `Missing unit conversion`, when it is a missing unit conversion, but the same error is being applied to two different situations.

**Comment by ehwenk** [comment] 2023-09-06 23:03
@yangsophieee Can you add a simple test for this too - in one of your existing test datasets, add two rows of data (can be a duplicate of another column or just be filled with a single value - the values don't matter), then in the metadata for one add a mis-spelled trait name and in the other units that don't have a unit conversion? And then confirm that the rows of data land in excluded data?

**Comment by yangsophieee** [comment] 2023-09-08 07:40
> @yangsophieee Can you add a simple test for this too - in one of your existing test datasets, add two rows of data (can be a duplicate of another column or just be filled with a single value - the values don't matter), then in the metadata for one add a mis-spelled trait name and in the other units that don't have a unit conversion? And then confirm that the rows of data land in excluded data?

I've added tests to `Test_2023_1`, and I think misspelled trait name isn't working, it still shows as "Missing unit conversion".

**Closed** 2023-09-20 02:33 UTC
Labels: dataset input
