### ISSUE TITLE
Test fails for `tutorial_dataset_1`

### ISSUE THREAD

**Issue by hrlai** [traitecoevo/traits.build#179] opened 2024-11-26 22:33 UTC
Hi again, was unable to pass the test while following Tutorial 1:

```
> dataset_test("tutorial_dataset_1")
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 64 ]

── Error: tutorial_dataset_1 ───────────────────────────────────────────────────
<subscriptOutOfBoundsError/error/condition>
Error in `FUN(X[[i]], ...)`: subscript out of bounds
Backtrace:
    ▆
 1. └─base::sapply(metadata[["contexts"]], "[[", "context_property")
 2.   └─base::lapply(X = X, FUN = FUN, ...)
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 64 ]
```

Below is my YAML file just in case (I didn't manually fill in the unknown values.

```
source:
  primary:
    key: Tutorial_dataset
    bibtype: Article
    year: '2005'
    author: Daniel S. Falster and Mark Westoby
    journal: Journal of Ecology
    title: Alternative height strategies among 45 dicot rain forest species from tropical
      Queensland, Australia
    volume: '93'
    number: '3'
    pages: 521–535
    doi: 10.1111/j.0022-0477.2005.00992.x
    issn: 1365-2745
contributors:
  data_collectors:
  - last_name: unknown
    given_name: unknown
    ORCID: unknown
    affiliation: unknown
  assistants: unknown
  dataset_curators: unknown
dataset:
  data_is_long_format: no
  custom_R_code: .na
  collection_date: 2002-11/2002-11
  taxon_name: Species
  location_name: site
  description: unknown
  basis_of_record: unknown
  life_stage: unknown
  sampling_strategy: unknown
  original_file: unknown
  notes: unknown
locations:
  Atherton:
    site: Atherton
    description: Tropical rain forest vegetation
    latitude (deg): -17.117
    longitude (deg): 145.65
  Cape Tribulation:
    site: Cape Tribulation
    description: Complex mesophyll vine forest in tropical rain forest
    latitude (deg): -16.1
    longitude (deg): 145.45
contexts: .na
traits:
- var_in: LMA (mg mm-2)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
- var_in: Leaf nitrogen (mg mg-1)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
- var_in: leaf size (mm2)
  unit_in: unknown
  trait_name: unknown
  entity_type: unknown
  value_type: unknown
  basis_of_value: unknown
  replicates: unknown
  methods: unknown
substitutions: .na
taxonomic_updates: .na
exclude_observations: .na
questions: .na

```

**Comment by hrlai** [comment] 2024-11-27 00:49
So I followed the steps in Tutorial 1 and added the remaining info manually into the YAML, but strangely get the error:
```
> dataset_test("tutorial_dataset_1")
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 103 ]

── Failure: tutorial_dataset_1 ─────────────────────────────────────────────────
data/tutorial_dataset_1/metadata.yml	traits - `unit_in`'s should not contain: 'mm2'
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 103 ]
```

Not sure why, but leaf area should have mm2 as unit?

**Comment by ehwenk** [comment] 2024-11-27 04:06
@hrlai Regarding your first error, I think it is because you had not yet mapped in any of the traits, and therefore the traits table was empty. We have tried to detect such "fail points" and add in useful messages, but we may have missed this one.

**Comment by ehwenk** [comment] 2024-11-27 04:19
@hrlai Regarding the second error, I'm baffled, because your metadata file is 1) What I expected; 2) The same as our "answer key" in https://github.com/traitecoevo/traits.build-template/tree/master/data/tutorial_dataset_1/raw/metadata.yml; and 3) The output units for leaf area are also mm2, so a conversion shouldn't be required (https://github.com/traitecoevo/traits.build-template/blob/master/config/traits.yml line 151).

I'm curious if you were to open the file config/unit_conversions.csv in a text editor and add the following line to the bottom "mm2, mm2, x*1" if the problem is solved. I don't seem to get errors when I don't include rows for "same units in and out", but I have a memory someone else had a similar issue last year. 

If that fixes it, I need to go through the unit conversions file here and add quite a few lines!

**Comment by ehwenk** [comment] 2024-11-27 04:26
@hrlai Also, thanks for using traits.build and we'd love to hear more about what does and doesn't work for you, as we're continuing developing the package and want to keep eliminating bugs.

**Comment by hrlai** [comment] 2024-11-27 20:47
> @hrlai Regarding the second error, I'm baffled, because your metadata file is 1) What I expected; 2) The same as our "answer key" in https://github.com/traitecoevo/traits.build-template/tree/master/data/tutorial_dataset_1/raw/metadata.yml; and 3) The output units for leaf area are also mm2, so a conversion shouldn't be required (https://github.com/traitecoevo/traits.build-template/blob/master/config/traits.yml line 151).
> 
> I'm curious if you were to open the file config/unit_conversions.csv in a text editor and add the following line to the bottom "mm2, mm2, x*1" if the problem is solved. I don't seem to get errors when I don't include rows for "same units in and out", but I have a memory someone else had a similar issue last year.
> 
> If that fixes it, I need to go through the unit conversions file here and add quite a few lines!

Just for curiosity, I replaced mm2 with cm2 and it passed the test.

And then like you suspected, adding `mm2, mm2, x*1` to the last line of `config/unit_conversions.csv` solved the problem. Would be great if it ignore unit when it matches the default unit in `config/traits.yml` so you don't need to manually add another line to the conversion csv ... might be a pain when you add new traits in the future huh.

**Comment by ehwenk** [comment] 2024-12-05 21:03
@hrlai This should be fixed - I discovered there was a branch we'd never merged in that fixed this after it previously emerged. Fixed with: https://github.com/traitecoevo/traits.build/commit/129dcf5f627a23967abb9b24657afc8c39583ef5

**Closed by ehwenk** 2024-12-05 21:03 UTC

**Comment by hrlai** [comment] 2024-12-15 19:33
Hey just want to note, I was able to solve this but by installing the dev branch 
```
remotes::install_github("traitecoevo/traits.build", "develop")
```
The instruction on the GitHub main page doesn't say "develop" so some users may not be aware.
